name: CI
on:
  - push
  - pull_request
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0"
    steps:
      - uses: actions/checkout@v2
      - uses: pmmp/setup-php-action@247e08acd52c1465f8f144c162c88f079d8c1174
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
      - name: phpstan configure
        run: |
          cp .github/phpstan.neon.ci phpstan.neon
          composer install --ignore-platform-reqs
      - name: phpstan analyze
        run: |
          composer run phpstan
